"""Caption scoring client backed by cached text embeddings and SentenceTransformers."""

from __future__ import annotations

import hashlib
import threading
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np
from sentence_transformers import SentenceTransformer

from .base import LALMClient
from AudioRetrieval.embeddings import load_caption_embeddings


def _normalize(vec: np.ndarray, eps: float = 1e-9) -> np.ndarray:
    norm = np.linalg.norm(vec)
    if norm < eps:
        return vec
    return vec / norm


@dataclass
class _CaptionEntry:
    embedding: np.ndarray
    clip_id: str
    caption_index: int
    text: str


class TextEmbeddingCaptionClient(LALMClient):
    """
    Caption scoring client using SentenceTransformers and cached caption embeddings.

    This client expects a bundle generated by ``precompute_caption_embeddings.py``.
    Query texts are embedded on the fly with the specified SentenceTransformer model
    and compared against precomputed caption embeddings via cosine similarity.
    """

    def __init__(
        self,
        *,
        embedding_bundle_dir: str,
        model_name: Optional[str] = None,
        device: Optional[str] = None,
        normalize: Optional[bool] = None,
        batch_size: int = 64,
        query_prefix: Optional[str] = None,
    ) -> None:
        bundle = load_caption_embeddings(Path(embedding_bundle_dir))
        metadata = bundle.metadata
        self._bundle_dir = Path(embedding_bundle_dir)
        self._captions: Dict[str, List[_CaptionEntry]] = {}
        self._clip_to_entries: Dict[str, List[_CaptionEntry]] = {}

        embeddings = bundle.embeddings.astype(np.float32, copy=False)
        if embeddings.ndim != 2:
            raise ValueError("Embeddings array must be 2-D.")

        default_normalize = bool(metadata.get("normalize", False))
        self._normalize = normalize if normalize is not None else default_normalize

        for entry, vector in zip(bundle.index, embeddings):
            caption = entry.get("caption_text")
            clip_id = entry.get("clip_id", "")
            caption_idx = int(entry.get("caption_index", 0))
            if not isinstance(caption, str):
                continue
            key = caption.strip()
            vec = _normalize(vector) if self._normalize else vector
            entry_obj = _CaptionEntry(embedding=vec, clip_id=clip_id, caption_index=caption_idx, text=caption)
            self._captions.setdefault(key, []).append(entry_obj)
            self._clip_to_entries.setdefault(clip_id, []).append(entry_obj)

        if not self._captions:
            raise ValueError(f"No caption embeddings loaded from {embedding_bundle_dir}.")

        model_to_use = model_name or metadata.get("model_name")
        if not model_to_use:
            raise ValueError("Model name must be provided either via arguments or metadata.")

        self._model_name = model_to_use
        self._device = device or "auto"
        self._batch_size = max(1, int(batch_size))
        self._query_prefix = query_prefix or ""

        self._model = SentenceTransformer(self._model_name, device=None if self._device == "auto" else self._device)
        self._query_cache: Dict[str, np.ndarray] = {}
        self._cache_lock = threading.Lock()

    # ------------------------------------------------------------------ helpers
    def _format_query(self, query: str) -> str:
        if not self._query_prefix:
            return query
        return f"{self._query_prefix}{query}"

    def _encode_query(self, query: str) -> np.ndarray:
        formatted = self._format_query(query.strip())
        cache_key = hashlib.sha1(formatted.encode("utf-8")).hexdigest()
        with self._cache_lock:
            if cache_key in self._query_cache:
                return self._query_cache[cache_key]

        vec = self._model.encode(
            [formatted],
            batch_size=1,
            convert_to_numpy=True,
            normalize_embeddings=self._normalize,
            show_progress_bar=False,
        )[0].astype(np.float32, copy=False)
        if self._normalize:
            vec = _normalize(vec)

        with self._cache_lock:
            self._query_cache[cache_key] = vec
        return vec

    def _lookup_caption(self, caption: str) -> np.ndarray:
        entries = self._captions.get(caption.strip())
        if entries:
            if len(entries) == 1:
                return entries[0].embedding
            stack = np.stack([ent.embedding for ent in entries], axis=0)
            vec = stack.mean(axis=0)
            return _normalize(vec) if self._normalize else vec

        # Fallback: encode caption directly
        vec = self._model.encode(
            [caption.strip()],
            batch_size=1,
            convert_to_numpy=True,
            normalize_embeddings=self._normalize,
            show_progress_bar=False,
        )[0].astype(np.float32, copy=False)
        return _normalize(vec) if self._normalize else vec

    def _similarity(self, query_vec: np.ndarray, caption_vec: np.ndarray) -> float:
        if self._normalize:
            return float(np.dot(query_vec, caption_vec))
        denom = max(np.linalg.norm(query_vec) * np.linalg.norm(caption_vec), 1e-9)
        return float(np.dot(query_vec, caption_vec) / denom)

    # ------------------------------------------------------------------ protocol
    def score_audio(self, query: str, audio_path) -> float:
        raise NotImplementedError("Audio scoring is not supported by TextEmbeddingCaptionClient.")

    def score_caption(self, query: str, caption: str) -> float:
        query_vec = self._encode_query(query)
        caption_vec = self._lookup_caption(caption)
        return self._similarity(query_vec, caption_vec)

    def rank_audio(self, query: str, candidates):
        raise NotImplementedError("Audio ranking is not supported by TextEmbeddingCaptionClient.")

    def rank_captions(self, query: str, captions: List[str]) -> List[int]:
        query_vec = self._encode_query(query)
        scored = []
        for idx, caption in enumerate(captions):
            caption_vec = self._lookup_caption(caption)
            score = self._similarity(query_vec, caption_vec)
            scored.append((score, idx))
        scored.sort(key=lambda item: item[0], reverse=True)
        return [idx for _, idx in scored]

    def generate_caption(self, audio_path):
        clip_id = Path(audio_path).stem
        entries = self._clip_to_entries.get(clip_id)
        if not entries:
            raise RuntimeError(f"No cached caption available for clip_id '{clip_id}'.")
        return entries[0].text
